library(colorout)
library(data.table)
Sys.setenv("plotly_username"="sunggong")
Sys.setenv("plotly_api_key"="aoAu3uwtcXuXFS7FOLUg")
source("https://bioconductor.org/biocLite.R")
grDevices::X11.options(width = 4.5, height = 4, ypos = 0, xpos = 1000, pointsize = 10)
